variables:
  MYSQL_DATABASE: articles
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_ALLOW_EMPTY_PASSWORD: 1

test:
  image: node:latest
  services:
    - mysql:latest # The JS mysql-library does not yet support the newest mysql protocol
  script:
    - npm install -g flow-bin
    - cd server && npm install && npm test && flow check src
    - cd ../client && npm install && npm test
