variables:
  MYSQL_DATABASE: database
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_ALLOW_EMPTY_PASSWORD: 1

test:
  image: alpine:latest
  services:
    - mysql:5 # The JS mysql-library does not yet support the newest mysql protocol
    - node:latest
  script:
    # - npm install -g flow-bin
    - cd server && npm install && npm test
    - cd ../client && npm install && npm test
