image: node:latest

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: database
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: ""
  MYSQL_ALLOW_EMPTY_PASSWORD: 1

before_script:
  - npm install -g flow-bin
  - cd server && npm install
  - cd ../client && npm install

run_tests:
  stage: test
  image: node:latest
  script:
    - npm test
    - cd ../server && npm test
#  artifacts:
#    paths:
#      - client/coverage
#      - server/coverage


#pages:
#  stage: deploy
#  dependencies:
#    - run_tests
#  script:
#    - cd ../
#    - mkdir .public
#    - cp -r client/* .public
#    - cp -r server/* .public
#    - mv .public public
#
#  artifacts:
#    paths:
#      - public
#  only:
#    - master